import type { Edge, Node } from '@xyflow/react'
import type {
  BusinessRuleDefinition,
  CanvasSnapshot,
  GraphDocument,
  GuardrailDefinition,
  PersonaDefinition,
  RagPipelineConfig,
  SkillDefinition,
  StitchNodeData,
} from '../../types/graph'
import { slugify } from '../nodeRegistry'
import { MAIN_GRAPH_ID } from '../subgraphCanvas'
import { generatePythonCode } from './pythonGenerator'

const LANGSTITCH_GENERATOR_VERSION = '0.1.0'

function pkgName(doc: GraphDocument): string {
  return slugify(doc.name) || 'langstitch_graph'
}

/** Semantic version for the generated project, sourced from the document. */
function projectVersion(doc: GraphDocument): string {
  const v = doc.projectVersion?.trim()
  return v && v.length ? v : '0.1.0'
}

function modulePath(doc: GraphDocument, sub: string, file: string): string {
  return `src/${pkgName(doc)}/${sub}/${file}`
}

function pyModuleInit(): string {
  return '"""LangStitch generated module."""\n'
}

export function generateLangsmithJson(doc: GraphDocument): string {
  const obs = doc.settings?.observability
  const ev = doc.settings?.eval
  const pkg = pkgName(doc)
  const hasEvalDataset =
    ev?.enabled && Boolean(ev.datasetName?.trim() || ev.datasetId?.trim())
  return JSON.stringify(
    {
      version: '1.0',
      langsmith: {
        project_name: obs?.langsmith?.projectName ?? doc.name,
        api_key_env: obs?.langsmith?.apiKeyEnv ?? 'LANGCHAIN_API_KEY',
        tracing_v2: obs?.langsmith?.tracingV2 ?? true,
        endpoint: 'https://api.smith.langchain.com',
      },
      eval: {
        enabled: ev?.enabled ?? false,
        dataset_name: ev?.datasetName ?? '',
        dataset_id: ev?.datasetId ?? '',
        experiment_prefix: ev?.experimentPrefix ?? '',
        max_concurrency: ev?.maxConcurrency ?? 2,
        description: ev?.description ?? '',
      },
      ...(hasEvalDataset
        ? {
            // cycles 75, 135, 195, 255, 315, 375, 411, 435, 495, 555 — eval-dataset metadata in langsmith.json export
            'eval-dataset': {
              enabled: true,
              dataset_name: ev?.datasetName ?? '',
              dataset_id: ev?.datasetId ?? '',
            },
          }
        : {}),
      langstitch: {
        schema_version: '1.2',
        generator_version: LANGSTITCH_GENERATOR_VERSION,
        project_name: doc.name,
        python_version: '3.13',
        package: pkg,
        modules: {
          graphs: 'graphs/',
          nodes: 'nodes/',
          skills: 'skills/',
          prompts: 'prompts/',
          tools: 'tools/',
          resources: 'resources/',
          connections: 'connections/',
          guardrails: 'guardrails/',
          rules: 'rules/',
          personas: 'personas/',
          rag: 'rag/',
        },
        registries: {
          skills: (doc.skillRegistry ?? []).map((s) => s.id),
          guardrails: (doc.guardrailRegistry ?? []).map((g) => g.id),
          business_rules: (doc.businessRuleRegistry ?? []).map((r) => r.id),
          personas: (doc.personaRegistry ?? []).map((p) => p.id),
          rag_pipelines: (doc.ragPipelines ?? []).map((r) => r.id),
          components: (doc.componentRegistry ?? []).map((c) => c.id),
          tools: (doc.toolRegistry ?? []).map((t) => t.id),
          agents: (doc.agentRegistry ?? []).map((a) => a.id),
        },
      },
    },
    null,
    2,
  )
}

export function generateEvalRunnerModule(doc: GraphDocument): string {
  const obs = doc.settings?.observability
  const apiKeyEnv = obs?.langsmith?.apiKeyEnv ?? 'LANGCHAIN_API_KEY'
  const pkg = pkgName(doc)
  return `"""LangSmith eval runner — generated by LangStitch (SDK runtime).

Reads eval configuration from \`\`langsmith.json\`\` and runs the registered
LangStitch entrypoint graph against a LangSmith dataset. The runner boots the
SDK application so the same compiled graph that serves traffic is evaluated.
"""
from __future__ import annotations

import argparse
import json
import sys
from pathlib import Path

from langstitch import get_logger, get_secret

log = get_logger("${pkg}.eval_runner")


def load_eval_config() -> dict:
    path = Path(__file__).resolve().parents[2] / "langsmith.json"
    if not path.exists():
        path = Path("langsmith.json")
    with path.open(encoding="utf-8") as f:
        return json.load(f)


def _build_target():
    """Return a LangSmith target that invokes the SDK entrypoint graph."""
    try:
        from ${pkg}.server import bootstrap
    except Exception as exc:  # pragma: no cover - graph extra not installed
        log.warning("Falling back to stub target (%s)", exc)

        def stub(inputs: dict) -> dict:
            return {"output": "stub", "inputs": inputs}

        return stub

    app = bootstrap()

    def target(inputs: dict) -> dict:
        return app.invoke(dict(inputs))

    return target


def dry_run() -> int:
    cfg = load_eval_config()
    ev = cfg.get("eval", {})
    if not ev.get("enabled"):
        print(json.dumps({"ok": False, "message": "Eval not enabled in langsmith.json"}))
        return 1
    if not ev.get("dataset_name") and not ev.get("dataset_id"):
        print(json.dumps({"ok": False, "message": "Missing dataset_name or dataset_id"}))
        return 1
    print(json.dumps({"ok": True, "dry_run": True, "eval": ev}))
    return 0


def run_eval() -> int:
    cfg = load_eval_config()
    ev = cfg.get("eval", {})
    ls = cfg.get("langsmith", {})
    api_key_env = ls.get("api_key_env", "${apiKeyEnv}")
    if not get_secret(api_key_env):
        print(json.dumps({"ok": False, "message": f"Set {api_key_env} in environment"}))
        return 1
    dataset = ev.get("dataset_name") or ev.get("dataset_id")
    if not dataset:
        print(json.dumps({"ok": False, "message": "Missing dataset in eval config"}))
        return 1
    try:
        from langsmith import Client
        from langsmith.evaluation import evaluate
    except ImportError:
        print(json.dumps({"ok": False, "message": "Install langsmith: pip install langsmith"}))
        return 1

    client = Client()
    prefix = ev.get("experiment_prefix") or "${doc.name}"
    results = evaluate(
        _build_target(),
        data=dataset,
        experiment_prefix=prefix,
        max_concurrency=int(ev.get("max_concurrency", 2)),
        client=client,
    )
    print(json.dumps({"ok": True, "experiment": str(results)}))
    return 0


def main() -> None:
    parser = argparse.ArgumentParser(description="Run LangSmith eval for ${doc.name}")
    parser.add_argument("--dry-run", action="store_true", help="Validate eval config only")
    args = parser.parse_args()
    sys.exit(dry_run() if args.dry_run else run_eval())


if __name__ == "__main__":
    main()
`
}

function generateSkillModule(skill: SkillDefinition): string {
  const fn = slugify(skill.id)
  return `"""Skill: ${skill.name}"""

SKILL = {
    "id": "${skill.id}",
    "name": ${JSON.stringify(skill.name)},
    "description": ${JSON.stringify(skill.description)},
    "instructions": ${JSON.stringify(skill.instructions)},
    "tool_ids": ${JSON.stringify(skill.toolIds)},
    "persona_id": ${JSON.stringify(skill.personaId)},
    "prompt_template": ${JSON.stringify(skill.promptTemplate)},
    "tags": ${JSON.stringify(skill.tags)},
}


def apply_skill(state: dict) -> dict:
    """Execute skill logic against graph state."""
    return {"skill_${fn}": SKILL["instructions"]}
`
}

function generateGuardrailModule(g: GuardrailDefinition): string {
  const fn = slugify(g.id)
  return `"""Guardrail: ${g.name}"""

GUARDRAIL = {
    "id": "${g.id}",
    "name": ${JSON.stringify(g.name)},
    "type": "${g.type}",
    "action": "${g.action}",
    "severity": "${g.severity}",
    "enabled": ${g.enabled},
    "policy": ${JSON.stringify(g.policy)},
}


def check_${fn}(text: str) -> tuple[bool, str]:
    """Return (passed, message)."""
    if not GUARDRAIL["enabled"]:
        return True, "skipped"
    # Policy evaluation stub — replace with LLM or rules engine
    if GUARDRAIL["action"] == "block" and "forbidden" in text.lower():
        return False, GUARDRAIL["policy"]
    return True, "ok"
`
}

function generateRuleModule(r: BusinessRuleDefinition): string {
  const fn = slugify(r.id)
  return `"""Business rule: ${r.name}"""

RULE = {
    "id": "${r.id}",
    "name": ${JSON.stringify(r.name)},
    "condition": ${JSON.stringify(r.condition)},
    "action": ${JSON.stringify(r.action)},
    "priority": ${r.priority},
    "enabled": ${r.enabled},
}


def evaluate_${fn}(context: dict) -> bool:
    """Evaluate business rule against context."""
    if not RULE["enabled"]:
        return False
    # Condition stub — wire to rules engine or Python eval sandbox
    return bool(context.get("trigger_${fn}", False))
`
}

function generatePersonaModule(p: PersonaDefinition): string {
  return `"""Persona: ${p.name}"""

PERSONA = {
    "id": "${p.id}",
    "name": ${JSON.stringify(p.name)},
    "role": ${JSON.stringify(p.role)},
    "tone": ${JSON.stringify(p.tone)},
    "system_prompt": ${JSON.stringify(p.systemPrompt)},
    "constraints": ${JSON.stringify(p.constraints)},
    "vocabulary": ${JSON.stringify(p.vocabulary)},
}


def build_system_prompt() -> str:
    parts = [PERSONA["system_prompt"], f"Role: {PERSONA['role']}", f"Tone: {PERSONA['tone']}"]
    if PERSONA["constraints"]:
        parts.append(f"Constraints: {PERSONA['constraints']}")
    return "\\n".join(parts)
`
}

function generateRagPipelineModule(p: RagPipelineConfig): string {
  const fn = slugify(p.id)
  return `"""RAG pipeline: ${p.name}"""

PIPELINE = {
    "id": "${p.id}",
    "name": ${JSON.stringify(p.name)},
    "chunk_strategy": "${p.chunkStrategy}",
    "chunk_size": ${p.chunkSize},
    "chunk_overlap": ${p.chunkOverlap},
    "embedding_provider": "${p.embeddingProvider}",
    "embedding_model": ${JSON.stringify(p.embeddingModel)},
    "retrieval_mode": "${p.retrievalMode}",
    "vector_store": "${p.vectorStore}",
    "top_k": ${p.topK},
    "rerank_enabled": ${p.rerankEnabled},
    "rerank_model": ${JSON.stringify(p.rerankModel)},
    "source_paths": ${JSON.stringify(p.sourcePaths)},
}


def chunk_documents(texts: list[str]) -> list[str]:
    """Chunk source documents per pipeline config."""
    size = PIPELINE["chunk_size"]
    overlap = PIPELINE["chunk_overlap"]
    chunks: list[str] = []
    for text in texts:
        start = 0
        while start < len(text):
            chunks.append(text[start : start + size])
            start += max(size - overlap, 1)
    return chunks


def embed_chunks(chunks: list[str]) -> list[list[float]]:
    """Embed chunks — vector, vectorless, or hybrid per retrieval_mode."""
    mode = PIPELINE["retrieval_mode"]
    if mode == "vectorless":
        return [[float(i)] for i in range(len(chunks))]
    # Vector / hybrid stub embeddings
    return [[hash(c) % 1000 / 1000.0 for _ in range(8)] for c in chunks]


def retrieve(query: str, chunks: list[str], vectors: list[list[float]]) -> list[str]:
    """Retrieve top-k chunks by mode."""
    k = min(PIPELINE["top_k"], len(chunks))
    if PIPELINE["retrieval_mode"] == "vectorless":
        return chunks[:k]
    # Simple lexical fallback for hybrid/vector stub
    scored = sorted(chunks, key=lambda c: query.lower() in c.lower(), reverse=True)
    return scored[:k]


def run_${fn}(query: str, documents: list[str] | None = None) -> dict:
    """Run full RAG pipeline: chunk → embed → retrieve → context."""
    docs = documents or []
    chunks = chunk_documents(docs) if docs else []
    vectors = embed_chunks(chunks) if chunks else []
    context = retrieve(query, chunks, vectors)
    return {
        "query": query,
        "context": context,
        "sources": context,
        "pipeline_id": PIPELINE["id"],
        "mode": PIPELINE["retrieval_mode"],
    }
`
}

function generateNodeModules(
  doc: GraphDocument,
  canvasByGraph: Record<string, CanvasSnapshot>,
): Record<string, string> {
  const files: Record<string, string> = {}
  const pkg = pkgName(doc)
  const seen = new Set<string>()
  const imports: string[] = []

  for (const canvas of Object.values(canvasByGraph)) {
    for (const node of canvas.nodes) {
      if (node.data.kind === 'start' || node.data.kind === 'end') continue
      const fn = slugify(node.id)
      if (seen.has(fn)) continue
      seen.add(fn)
      imports.push(`from .${fn} import ${fn}`)

      files[modulePath(doc, 'nodes', `${fn}.py`)] = `"""Node: ${node.data.label} (${node.data.kind})"""
from ${pkg}.state import State


def ${fn}(state: State) -> dict:
    """${node.data.description ?? node.data.label}"""
    return {}
`
    }
  }

  files[modulePath(doc, 'nodes', '__init__.py')] = `${pyModuleInit()}${imports.join('\n')}\n`
  return files
}

/** Generate the SDK graph-server entrypoint module (``@langstitch_graph_server``). */
export function generateServerModule(doc: GraphDocument): string {
  const pkg = pkgName(doc)
  const slug = slugify(doc.name) || 'langstitch_graph'
  const version = projectVersion(doc)
  return `"""Graph API server — generated by LangStitch (SDK runtime)."""
from __future__ import annotations

from langstitch import LangStitchApp, langstitch_graph_server


@langstitch_graph_server(name="${slug}", protocol="http", host="0.0.0.0", port=8000, version="${version}")
class Server:
    """Graph API server for ${doc.name}."""


def bootstrap() -> LangStitchApp:
    """Import the package (registers components) and build the app runtime."""
    import ${pkg}  # noqa: F401 — triggers @graph / @graph_node registration

    return LangStitchApp.bootstrap()


def create_app():
    """FastAPI app exposing /health, /info, and /invoke (needs langstitch[server])."""
    return Server.create_app()


def main() -> None:
    """Run the HTTP server (needs langstitch[server])."""
    Server.serve()


if __name__ == "__main__":
    main()
`
}

/**
 * Generate a Helm chart for the graph server under ``deploy/helm/<slug>/``.
 * Includes Chart.yaml, values.yaml, and templates/ (deployment, service, helpers).
 */
export function generateHelmChart(doc: GraphDocument): Record<string, string> {
  // Helm/Kubernetes names must be DNS-1123: lowercase alphanumerics and dashes.
  const slug = (slugify(doc.name) || 'langstitch-graph').replace(/_/g, '-')
  const version = projectVersion(doc)
  const base = `deploy/helm/${slug}`
  const obs = doc.settings?.observability
  const lsEnabled = Boolean(obs?.langsmith?.enabled)
  const lsProject = obs?.langsmith?.projectName ?? doc.name

  const files: Record<string, string> = {}

  files[`${base}/Chart.yaml`] = `apiVersion: v2
name: ${slug}
description: Helm chart for ${doc.name} — LangStitch graph server
type: application
version: ${version}
appVersion: "${version}"
`

  files[`${base}/values.yaml`] = `# Default values for ${slug}.
replicaCount: 1

image:
  repository: ${slug}
  tag: "${version}"
  pullPolicy: IfNotPresent

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

service:
  type: ClusterIP
  port: 8000

resources: {}
  # limits:
  #   cpu: 500m
  #   memory: 512Mi
  # requests:
  #   cpu: 250m
  #   memory: 256Mi

autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 5
  targetCPUUtilizationPercentage: 80

# Extra environment variables injected into the container.
env: []
  # - name: OPENAI_API_KEY
  #   valueFrom:
  #     secretKeyRef:
  #       name: ${slug}-secrets
  #       key: openai-api-key

langsmith:
  enabled: ${lsEnabled}
  project: ${JSON.stringify(lsProject)}
  apiKeyEnv: ${JSON.stringify(obs?.langsmith?.apiKeyEnv ?? 'LANGCHAIN_API_KEY')}
`

  files[`${base}/.helmignore`] = `.DS_Store
.git/
.gitignore
*.tmp
`

  files[`${base}/templates/_helpers.tpl`] = `{{- define "${slug}.name" -}}
{{- default .Chart.Name .Values.nameOverride | trunc 63 | trimSuffix "-" -}}
{{- end -}}

{{- define "${slug}.fullname" -}}
{{- if .Values.fullnameOverride -}}
{{- .Values.fullnameOverride | trunc 63 | trimSuffix "-" -}}
{{- else -}}
{{- printf "%s-%s" .Release.Name (include "${slug}.name" .) | trunc 63 | trimSuffix "-" -}}
{{- end -}}
{{- end -}}

{{- define "${slug}.labels" -}}
app.kubernetes.io/name: {{ include "${slug}.name" . }}
app.kubernetes.io/instance: {{ .Release.Name }}
app.kubernetes.io/version: {{ .Chart.AppVersion | quote }}
app.kubernetes.io/managed-by: {{ .Release.Service }}
helm.sh/chart: {{ printf "%s-%s" .Chart.Name .Chart.Version }}
{{- end -}}

{{- define "${slug}.selectorLabels" -}}
app.kubernetes.io/name: {{ include "${slug}.name" . }}
app.kubernetes.io/instance: {{ .Release.Name }}
{{- end -}}
`

  files[`${base}/templates/deployment.yaml`] = `apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "${slug}.fullname" . }}
  labels:
    {{- include "${slug}.labels" . | nindent 4 }}
spec:
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "${slug}.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "${slug}.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: {{ .Values.service.port }}
              protocol: TCP
          env:
            {{- if .Values.langsmith.enabled }}
            - name: LANGCHAIN_TRACING_V2
              value: "true"
            - name: LANGCHAIN_PROJECT
              value: {{ .Values.langsmith.project | quote }}
            {{- end }}
            {{- with .Values.env }}
            {{- toYaml . | nindent 12 }}
            {{- end }}
          livenessProbe:
            httpGet:
              path: /health
              port: http
            initialDelaySeconds: 10
          readinessProbe:
            httpGet:
              path: /health
              port: http
            initialDelaySeconds: 5
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
`

  files[`${base}/templates/service.yaml`] = `apiVersion: v1
kind: Service
metadata:
  name: {{ include "${slug}.fullname" . }}
  labels:
    {{- include "${slug}.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "${slug}.selectorLabels" . | nindent 4 }}
`

  files[`${base}/templates/hpa.yaml`] = `{{- if .Values.autoscaling.enabled }}
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: {{ include "${slug}.fullname" . }}
  labels:
    {{- include "${slug}.labels" . | nindent 4 }}
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: {{ include "${slug}.fullname" . }}
  minReplicas: {{ .Values.autoscaling.minReplicas }}
  maxReplicas: {{ .Values.autoscaling.maxReplicas }}
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: {{ .Values.autoscaling.targetCPUUtilizationPercentage }}
{{- end }}
`

  return files
}

export function generatePythonProject(
  doc: GraphDocument,
  projectJson: string,
  nodes: Node<StitchNodeData>[],
  edges: Edge[],
  canvasByGraph?: Record<string, CanvasSnapshot>,
): Record<string, string> {
  const pkg = pkgName(doc)
  const canvases = canvasByGraph ?? { [MAIN_GRAPH_ID]: { nodes, edges } }
  const monolith = generatePythonCode(doc, nodes, edges, canvases)
  const files: Record<string, string> = {}

  const version = projectVersion(doc)
  files['pyproject.toml'] = `[project]
name = "${pkg}"
version = "${version}"
description = ${JSON.stringify(doc.description ?? doc.name)}
requires-python = ">=3.10"
readme = "README.md"
dependencies = [
  "langstitch[graph,server]>=0.1.0",
]

[project.optional-dependencies]
rag = [
  "langchain-text-splitters>=0.3.0",
  "chromadb>=0.5.0",
]
dev = ["pytest>=8.0", "build>=1.0", "langsmith>=0.2.0"]

[project.scripts]
${pkg} = "${pkg}.__main__:main"

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[tool.hatch.build.targets.wheel]
packages = ["src/${pkg}"]

[tool.pytest.ini_options]
testpaths = ["tests"]
pythonpath = ["src"]
`

  files['langsmith.json'] = generateLangsmithJson(doc)
  files[`src/${pkg}/eval_runner.py`] = generateEvalRunnerModule(doc)
  files['langstitch.project.json'] = projectJson
  const helmSlug = (slugify(doc.name) || 'langstitch-graph').replace(/_/g, '-')
  files['README.md'] = `# ${doc.name}

Generated by [LangStitch](https://github.com/vijayptiwari/LangStitch) on the
**LangStitch SDK** (\`langstitch[graph,server]\`).

## Requirements

- Python **3.10+**

## Setup

\`\`\`bash
python -m venv .venv
source .venv/bin/activate  # Windows: .venv\\Scripts\\activate
pip install -e ".[dev]"
\`\`\`

## Run

\`\`\`bash
${pkg}                 # bootstrap the app and print info
python -m ${pkg}       # same as above
python -m ${pkg}.app.server   # start the HTTP graph server (langstitch[server])
\`\`\`

## Test

\`\`\`bash
pytest
\`\`\`

## Evaluate

\`\`\`bash
python src/${pkg}/eval_runner.py --dry-run   # validate langsmith.json eval config
python src/${pkg}/eval_runner.py             # run LangSmith eval (needs LANGCHAIN_API_KEY)
\`\`\`

## Deploy (Helm)

\`\`\`bash
helm upgrade --install ${helmSlug} deploy/helm/${helmSlug}
\`\`\`

## Project layout

\`\`\`
src/${pkg}/
  app/          # @langstitch_graph_server entrypoint (server + bootstrap)
  graphs/       # @graph builders (GraphBuilder assembly)
  nodes/        # @graph_node handlers
  skills/       # Skill modules
  prompts/      # Prompt templates
  tools/        # Tool registry
  resources/    # Static resources
  connections/  # MCP, remote, A2A
  guardrails/   # Input/output guardrails
  rules/        # Business rules
  personas/     # Agent personas
  rag/          # RAG pipelines (chunk, embed, retrieve)
  eval_runner.py
deploy/helm/${helmSlug}/   # Kubernetes Helm chart
\`\`\`

Import \`langsmith.json\` in LangStitch IDE to restore project metadata.
`

  files['.gitignore'] = `.venv/
__pycache__/
*.pyc
.pytest_cache/
dist/
*.egg-info/
.env
`

  files[`src/${pkg}/__init__.py`] = `"""${doc.name} — LangStitch generated package."""
# Import subpackages so their @graph / @graph_node / @langstitch_graph_server
# decorators register on the global LangStitch registry.
from . import graphs  # noqa: F401
from . import app  # noqa: F401

__version__ = "${version}"
`

  files[`src/${pkg}/__main__.py`] = `"""CLI entrypoint — bootstrap the SDK app and print its info."""
import json

from ${pkg}.app.server import bootstrap


def main() -> None:
    app = bootstrap()
    print(json.dumps(app.info(), indent=2))


if __name__ == "__main__":
    main()
`

  const stateMatch = monolith.match(/from typing[\s\S]*?class State\(TypedDict\):[\s\S]*?(?=\n\n#|\n\ndef |\nimport os)/)
  files[`src/${pkg}/state.py`] = stateMatch
    ? `${stateMatch[0].trim()}\n`
    : `from typing import Annotated, TypedDict\nfrom langgraph.graph.message import add_messages\n\n\nclass State(TypedDict):\n    messages: Annotated[list, add_messages]\n`

  files[`src/${pkg}/config.py`] = `"""Runtime configuration."""
import os

LANGSMITH_PROJECT = os.environ.get("LANGCHAIN_PROJECT", "${doc.settings?.observability?.langsmith?.projectName ?? doc.name}")
LANGSMITH_TRACING = os.environ.get("LANGCHAIN_TRACING_V2", "${doc.settings?.observability?.langsmith?.tracingV2 ? 'true' : 'false'}")
`

  files[`src/${pkg}/graphs/__init__.py`] = `${pyModuleInit()}from . import main  # noqa: F401\n`
  files[`src/${pkg}/graphs/main.py`] = monolith

  // Skills
  files[`src/${pkg}/skills/__init__.py`] = pyModuleInit()
  for (const skill of doc.skillRegistry ?? []) {
    files[`src/${pkg}/skills/${slugify(skill.id)}.py`] = generateSkillModule(skill)
  }

  // Guardrails
  files[`src/${pkg}/guardrails/__init__.py`] = pyModuleInit()
  for (const g of doc.guardrailRegistry ?? []) {
    files[`src/${pkg}/guardrails/${slugify(g.id)}.py`] = generateGuardrailModule(g)
  }

  // Business rules
  files[`src/${pkg}/rules/__init__.py`] = pyModuleInit()
  for (const r of doc.businessRuleRegistry ?? []) {
    files[`src/${pkg}/rules/${slugify(r.id)}.py`] = generateRuleModule(r)
  }

  // Personas
  files[`src/${pkg}/personas/__init__.py`] = pyModuleInit()
  for (const p of doc.personaRegistry ?? []) {
    files[`src/${pkg}/personas/${slugify(p.id)}.py`] = generatePersonaModule(p)
  }

  // RAG
  files[`src/${pkg}/rag/__init__.py`] = `${pyModuleInit()}from .pipeline import list_pipelines\n`
  files[`src/${pkg}/rag/pipeline.py`] = `${(doc.ragPipelines ?? []).length ? (doc.ragPipelines ?? []).map((p) => {
    const id = slugify(p.id)
    return `from .${id} import run_${id}, PIPELINE as PIPELINE_${id.toUpperCase()}`
  }).join('\n') : '# No RAG pipelines defined'}

PIPELINES = {
${(doc.ragPipelines ?? []).map((p) => `    "${p.id}": "${slugify(p.id)}",`).join('\n')}
}


def list_pipelines() -> list[str]:
    return list(PIPELINES.keys())


def run_pipeline(pipeline_id: str, query: str, documents: list[str] | None = None) -> dict:
    from importlib import import_module
    slug = PIPELINES.get(pipeline_id, pipeline_id)
    mod = import_module(f".{slug}", package=__name__)
    return getattr(mod, f"run_{slug}")(query, documents)
`
  for (const p of doc.ragPipelines ?? []) {
    files[`src/${pkg}/rag/${slugify(p.id)}.py`] = generateRagPipelineModule(p)
  }

  // Prompts
  files[`src/${pkg}/prompts/__init__.py`] = pyModuleInit()
  files[`src/${pkg}/prompts/templates.py`] = `# Prompt templates\nPROMPTS = {}\n`

  // Tools
  files[`src/${pkg}/tools/__init__.py`] = pyModuleInit()
  files[`src/${pkg}/tools/registry.py`] = `TOOL_REGISTRY = {
${(doc.toolRegistry ?? []).map((t) => `    "${t.id}": {"name": ${JSON.stringify(t.name)}, "source": "${t.source}"},`).join('\n')}
}
`

  // Resources & connections
  files[`src/${pkg}/resources/__init__.py`] = pyModuleInit()
  files[`src/${pkg}/connections/__init__.py`] = pyModuleInit()
  files[`src/${pkg}/connections/mcp.py`] = `# MCP connections\nMCP_SERVERS = {}\n`
  files[`src/${pkg}/connections/remote.py`] = `# Remote graph connections\nREMOTE_GRAPHS = {}\n`

  // Node modules (per-node files)
  Object.assign(files, generateNodeModules(doc, canvases))

  // app package — @langstitch_graph_server entrypoint
  files[`src/${pkg}/app/__init__.py`] = `${pyModuleInit()}from . import server  # noqa: F401\n`
  files[`src/${pkg}/app/server.py`] = generateServerModule(doc)

  // Container image (used by the Helm chart's image.repository)
  files['Dockerfile'] = `FROM python:3.12-slim
WORKDIR /app
COPY pyproject.toml README.md ./
COPY src ./src
RUN pip install --no-cache-dir ".[dev]"
EXPOSE 8000
CMD ["python", "-m", "${pkg}.app.server"]
`

  // Tests
  files['tests/test_smoke.py'] = `"""Smoke tests — verify SDK registration and graph compilation."""
import pytest


def test_import_package():
    import ${pkg}
    assert ${pkg}.__version__


def test_entrypoint_graph_registered():
    import ${pkg}  # noqa: F401 — triggers decorator registration
    from langstitch import get_registry

    reg = get_registry()
    assert reg.entrypoint_graph() is not None
    assert reg.server is not None


def test_graph_compiles():
    from ${pkg}.graphs.main import graph

    assert graph is not None
`

  files['tests/__init__.py'] = ''

  // Helm chart under deploy/helm/<slug>/
  Object.assign(files, generateHelmChart(doc))

  return files
}
