"""Run a graph file generated by LG Canvas."""

import importlib.util
import sys
from pathlib import Path


def load_graph_module(path: Path):
    spec = importlib.util.spec_from_file_location("generated_graph", path)
    if spec is None or spec.loader is None:
        raise RuntimeError(f"Cannot load module from {path}")
    module = importlib.util.module_from_spec(spec)
    sys.modules["generated_graph"] = module
    spec.loader.exec_module(module)
    return module


def main():
    if len(sys.argv) < 2:
        print("Usage: python run_graph.py <path-to-generated.py>")
        sys.exit(1)

    path = Path(sys.argv[1])
    if not path.exists():
        print(f"File not found: {path}")
        sys.exit(1)

    module = load_graph_module(path)
    graph = getattr(module, "graph", None)
    if graph is None:
        print("No `graph` object found in generated file.")
        sys.exit(1)

    result = graph.invoke({"messages": []})
    print("Graph result:")
    print(result)


if __name__ == "__main__":
    main()
